Implement Clear function
bencefarkas200/to-do pull request #5
Opened 2024-01-08 08:49 UTC by bencefarkas200

When 'Clear' button is clicked done tasks get deleted from db too.

2024-01-09 10:10 UTC, gy-szabo requested changes

2024-01-09 10:10 UTC, gy-szabo commented on front-end/src/app/task.service.ts
> +    return this.http.delete<Task>(this.url);
What the endpoint returns on the server side, and what the client says the server will return does not match. These should always be uniform.

2024-01-09 10:10 UTC, gy-szabo commented on front-end/src/app/app.component.ts
>    doneClear() {
This function name is a bit weird, because knowing the context is needed to understand what this function does. I'd say `clearDoneArray` would be more clean and intuitive, and therefore it would also be easier to guess what it actually does.

2024-01-09 10:10 UTC, gy-szabo commented on back-end/src/model/TaskDTO.ts
> +  _id?: string;
How come this change is needed?

2024-01-09 10:10 UTC, gy-szabo commented on back-end/src/task/task.controller.ts
> +    return this.taskService.deleteDone();
Clean code function name problems here as well, to me `deleteDone` means delete one task with done status. Please modify the function name so it reflects clearly what it does.

2024-01-10 11:31 UTC, bencefarkas200 commented on back-end/src/model/TaskDTO.ts
> +  _id?: string;
I'm not really sure why I did this :D... Probably wanted `Task `and `TaskDTO `to be the same, that's why I made the `id` optional. But you're totally right, it's not needed.

2024-01-10 12:21 UTC, gy-szabo commented on back-end/src/model/TaskDTO.ts
> +  _id?: string;
Understandable. 😀 Btw the best thing would be to use the same exact class on both the frontend and on the backend side, using a shared library. However it's okay like this for now

2024-01-10 12:27 UTC, merged